version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3c73t-p4
      POSTGRES_DB: local_db
    volumes: 
      - pg_data:/var/lib/postgresql/data
    tty: true
  backend:
    container_name: backend
    # restart: on-failure
    build: 
      context: .
    env_file:
      .env
    depends_on:
      - postgres
    volumes:
      - .:/backend/
      - /backend/node_modules
    environment:
      PGUSER: postgres
      PGPASSWORD: s3c73t-p4
      PGDATABASE: local_db
      PGHOST: postgres
      # NODE_ENV: developments
      PORT: 3001
    ports:
      - "3001:3001"
      - 127.0.0.1:9223:9223
    command: npm run start
  migration: 
    build:
      context: ./
    command: [
      "./wait-for-it/wait-for-it.sh",
      "postgres:5432",
      "--", 
      "npm",
      "run",
      "migrate",
    ]
    links: 
      - postgres
    depends_on:
      - postgres
    env_file:
      .env
    environment: 
      PGUSER: postgres
      PGPASSWORD: s3c73t-p4
      PGDATABASE: local_db
      PGHOST: postgres
    
volumes:
  database:
  pg_data: null

  